steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/dice-master-the-platform/hawkeye/processing:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/dice-master-the-platform/hawkeye/processing:latest'
options:
  logging: CLOUD_LOGGING_ONLY
