substitutions:
  _VITE_GOOGLE_CLIENT_ID: ""
  _VITE_GOOGLE_CLIENT_SECRET: ""
  _VITE_API_BASE: ""
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}"
      - "--build-arg"
      - "VITE_GOOGLE_CLIENT_SECRET=${_VITE_GOOGLE_CLIENT_SECRET}"
      - "--build-arg"
      - "VITE_API_BASE=${_VITE_API_BASE}"
      - "-t"
      - "us-central1-docker.pkg.dev/dice-master-the-platform/hawkeye/frontend-user:latest"
      - "."
images:
  - "us-central1-docker.pkg.dev/dice-master-the-platform/hawkeye/frontend-user:latest"
options:
  logging: CLOUD_LOGGING_ONLY
